version: '3.7'
services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - 4000:4000
    tty: true
      # - 4200:4200
      # - 9876:9876
    environment:
      - TERM=xterm-256color`
    #   # - CHOKIDAR_USEPOLLING=true