version: '3.7'
services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ${PWD}:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4200:4200
      - 9876:9876
    environment:
      - CHOKIDAR_USEPOLLING=true